apiVersion: v1
kind: Service
metadata:
  name: asset-api
  namespace: dev-demo-app
  labels:        
    app: asset-api
spec:
  selector:
    app: asset-api
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
  type: LoadBalancer
