name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: us-east-1             

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # --- Setup Python & Tests ---
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt


      # --- AWS Credentials ---
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # --- Docker Build & Push ---
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPO }}:latest ./app

      - name: Push to Amazon ECR
        run: |
          docker push ${{ secrets.ECR_REPO }}:latest

      # Deployer sur EKS
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name devops-demo-eks --region ${{ secrets.AWS_REGION }}

      - name: Deploy to EKS
        run: |
          kubectl set image  deployment/asset-api asset-api=${{ secrets.ECR_REPO }}:latest -n dev-demo-app

      # SMOKE TESTS
      - name: Wait for asset-api pod readiness
        run: |
          kubectl rollout status deployment/asset-api -n dev-demo-app --timeout=120s

      - name: Port-forward asset-api service
        run: |
          kubectl port-forward svc/asset-api 5000:5000 -n dev-demo-app &
          sleep 5

      - name: Smoke test /metrics
        run: |
          # On teste si la métrique custom existe bien
          curl -s http://$API_IP:5000/metrics | grep 'it_assets_count'

      - name: Smoke test /assets
        run: |
          curl -sf http://$API_IP:5000/assets | grep -E '\[|\{' || exit 1



